### PR TITLE
Dependencies for newer versions of puma

### PR DESCRIPTION
**Pull request by chuttam**

### CODE REVIEW

**Comment by chuttam** [comment]
@carhartl Didn't resolve the dependency problem as I expected :(

I pushed to registry anyway to try. This is the message from wercker when trying to install 2.16.0 of puma gem:

https://app.wercker.com/#buildstep/56ad3f6c7bcbc9936006975d

Any thoughts?

**Comment by carhartl** [comment]
I'd try `sudo apt-get install build-essential`.

**Comment by carhartl** [comment]
If that doesn't succeed use a hammer:

`sudo apt-get install build-essential bison openssl libreadline6 libreadline6-dev curl git-core zlib1g zlib1g-dev libssl-dev libyaml-dev libxml2-dev autoconf libc6-dev ncurses-dev automake libtool`

**Comment by chuttam** [comment]
Hahaha.... I wasn't sure how "pure" or "thin" you wanted to keep the dependency set, so I didn't resort to too much pollution. I will now! :)

I think the missing piece was `openssl`. Will try with that first, and if not, it's :hammer: time.

**Comment by chuttam** [comment]
Also, can you grant me push access on the repo please? Thanks.

**Comment by chuttam** [comment]
Bah... didn't work with `openssl` and `build-essential`. I guess I just have to pull trusty container locally, and try every `apt-get` I can think of for puma 2.16.0

Just to make sure I'm not doing anything stupid... I just change `werker-box.yml`, and then push my branch to `registry` in werker. Is there something I'm missing @carhartl ?

Most recent box deploy: [success](https://app.wercker.com/#deploy/56afe72a68076eba3b28fe57) 
Most recent attempt to use new box: [failure](https://app.wercker.com/#buildstep/56b024d77bcbc993600bff86)

**Comment by carhartl** [comment]
I can't think of anything else. Maybe try to bump the version declaration in line 2: `version: 0.0.1`, though that didn't seem necessary for me.

**Comment by chuttam** [comment]
Gem updates still failed with base library dependency failures. Didn't merge.

**Pull request closed without merging**
